version: "3"
services:
  hapi-fhir-postgres:
    image: postgres:14.2
    container_name: hapi-fhir-postgres
    restart: always
    environment:
      POSTGRES_DB: "hapi"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    expose:
      - 5432
    volumes:
      - hapi-fhir-postgres:/var/lib/postgresql/data
  hapi-fhir-jpaserver-start:
    build: .
    container_name: hapi-fhir-jpaserver-start
    #restart: on-failure
    environment:
      spring.datasource.url: "jdbc:postgresql://hapi-fhir-postgres:5432/hapi"
    ports:
      - "8080:8080"
    depends_on:
      - hapi-fhir-postgres
volumes:
  hapi-fhir-postgres:
